"""add inbox table

Revision ID: e8170c01cdbc
Revises: 8ea3e95dc42c
Create Date: 2026-09-09 22:14:23.898581

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8170c01cdbc"
down_revision: Union[str, Sequence[str], None] = "8ea3e95dc42c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index("ix_inbox_created_at", "inbox", ["created_at"], unique=False)
    op.create_index("ix_inbox_event_id", "inbox", ["event_id"], unique=False)
    op.create_index("ix_inbox_status", "inbox", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inbox_status", table_name="inbox")
    op.drop_index("ix_inbox_event_id", table_name="inbox")
    op.drop_index("ix_inbox_created_at", table_name="inbox")
    op.drop_table("inbox")
    # ### end Alembic commands ###
