"""Add payment_id column to orders

Revision ID: ff6bdd83cbeb
Revises: d4b9574c298a
Create Date: 2026-08-28 17:48:13.421611

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff6bdd83cbeb"
down_revision: Union[str, Sequence[str], None] = "d4b9574c298a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("payment_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_id")
    # ### end Alembic commands ###
